[versions]
# libraries
junit = "4.13.2"
junit-jupiter = "5.14.1"
junit-platform-launcher = "1.14.1"
assertj = "3.27.7"

# plugins
kotlin = "2.4.0"
changelog = "2.5.0"
intelliJPlatform = "2.19.0"
lombok = "9.5.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
